# Generated by Django 5.1.4 on 2024-12-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_id', models.CharField(max_length=255)),
                ('max', models.DecimalField(decimal_places=4, max_digits=4)),
                ('min', models.DecimalField(decimal_places=4, max_digits=4)),
                ('avg', models.DecimalField(decimal_places=4, max_digits=4)),
                ('no_of_records', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('org_id', models.CharField(max_length=255)),
            ],
        ),
    ]
