# Generated by Django 5.1.4 on 2024-12-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings_element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('element_name', models.CharField(max_length=255)),
                ('machine_code', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='settings_org',
            fields=[
                ('company_code', models.CharField(max_length=255)),
                ('plant_code', models.CharField(max_length=255)),
                ('line_code', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
