# Generated by Django 5.1.4 on 2024-12-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0002_settings_element_settings_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='settings_element',
        ),
        migrations.DeleteModel(
            name='settings_org',
        ),
    ]
