# Generated by Django 5.1.4 on 2024-12-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0004_settings_element_settings_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatalog',
            name='avg',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sensordatalog',
            name='max',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sensordatalog',
            name='min',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
