# Generated by Django 5.1.4 on 2024-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0005_alter_sensordatalog_avg_alter_sensordatalog_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_org',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
