# Generated by Django 5.1.4 on 2024-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0007_settings_element_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=255)),
                ('element_name', models.CharField(max_length=255)),
                ('machine_code', models.CharField(max_length=255)),
                ('element_type', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('prediction', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Settings_Org',
            new_name='SettingsOrg',
        ),
        migrations.DeleteModel(
            name='Settings_Element',
        ),
    ]
