# Generated by Django 5.1.4 on 2024-12-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0008_settingselement_rename_settings_org_settingsorg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingselement',
            name='org_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingselement',
            name='server_ip',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingselement',
            name='tag',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
