# Generated by Django 5.1.4 on 2025-01-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0009_settingselement_org_id_settingselement_server_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('error_category', models.CharField(max_length=255)),
                ('error_text', models.TextField()),
                ('severity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
