# Generated by Django 5.1.4 on 2025-01-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0012_modellog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelLog',
        ),
    ]
