# Generated by Django 5.1.4 on 2025-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0013_delete_modellog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('model_path', models.CharField(max_length=255)),
                ('model_created', models.BooleanField()),
                ('remarks', models.TextField()),
                ('log_time', models.DateTimeField()),
            ],
        ),
    ]
