# Generated by Django 5.1.4 on 2025-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0014_modellog'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingselement',
            name='model_path',
            field=models.CharField(default='model not created', max_length=255),
        ),
    ]
