# Generated by Django 5.1.4 on 2025-01-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0015_settingselement_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatalog',
            name='rec_train_data',
            field=models.BooleanField(default=False),
        ),
    ]
