# Generated by Django 5.1.4 on 2025-01-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0016_sensordatalog_rec_train_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingselement',
            name='rec_train_data',
            field=models.BooleanField(default=False),
        ),
    ]
