# Generated by Django 5.1.4 on 2025-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0017_settingselement_rec_train_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingselement',
            name='lower_anamoly_limit',
            field=models.CharField(default='model not created', max_length=255),
        ),
        migrations.AddField(
            model_name='settingselement',
            name='upper_anamoly_limit',
            field=models.CharField(default='model not created', max_length=255),
        ),
    ]
