# Generated by Django 5.1.5 on 2025-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0018_settingselement_lower_anamoly_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingselement',
            name='aggregation_type',
            field=models.CharField(default='model not created', max_length=255),
        ),
    ]
