# Generated by Django 5.1.5 on 2025-02-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0019_settingselement_aggregation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDataLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_id', models.CharField(max_length=255)),
                ('element_name', models.CharField(max_length=255)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=8)),
                ('aggregation_type', models.CharField(max_length=255)),
                ('no_of_records', models.CharField(max_length=255)),
                ('anomaly_ranges', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('org_id', models.CharField(max_length=255)),
                ('time_stamp', models.CharField(max_length=255)),
                ('is_prev', models.BooleanField(default=False)),
            ],
        ),
    ]
