# Generated by Django 5.1.5 on 2025-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0020_anomalydatalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalydatalog',
            name='is_prev',
        ),
        migrations.AddField(
            model_name='anomalydatalog',
            name='new_anamoly',
            field=models.BooleanField(default=True),
        ),
    ]
