# Generated by Django 5.1.5 on 2025-02-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0021_remove_anomalydatalog_is_prev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsEmailRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('org_id', models.IntegerField()),
                ('recipient_type', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
