# Generated by Django 5.1.5 on 2025-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0022_settingsemailrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsemailrecipients',
            name='recipient_type',
            field=models.CharField(choices=[('To', '1'), ('CC', '2'), ('Bcc', '3')], default='To', max_length=255),
        ),
    ]
