# Generated by Django 5.1.5 on 2025-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0019_anomalydatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordatalog',
            name='machine',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='settingselement',
            name='aggregation_type',
            field=models.CharField(default='model not created', max_length=255),
        ),
    ]
