# Generated by Django 5.1.5 on 2025-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0020_sensordatalog_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatalog',
            name='machine',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
