# Generated by Django 5.1.5 on 2025-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0021_alter_sensordatalog_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatalog',
            name='machine',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
