# Generated by Django 5.1.5 on 2025-02-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictive', '0022_alter_sensordatalog_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordatalog',
            name='machine',
        ),
    ]
